packages/synchro-charts-react/package.json

* Bump @synchro-charts/react to 1.0.5
* Bump @synchro-charts/core to 1.0.3 in @synchro-charts/react
https://github.com/awslabs/synchro-charts/actions/runs/1441445611

Bump @synchro-charts/react to 1.0.5

---

packages/synchro-charts/src/components.d.ts

Build and include typescript types for type changes previously made.

fix: include updated types

---

CHANGELOG.md
lerna.json
packages/doc-site/CHANGELOG.md
packages/doc-site/package.json
packages/synchro-charts-react/CHANGELOG.md
packages/synchro-charts-react/package.json
packages/synchro-charts/CHANGELOG.MD
packages/synchro-charts/package.json

release version 4.0.1

---

CHANGELOG.md
lerna.json
packages/doc-site/CHANGELOG.md
packages/doc-site/package.json
packages/synchro-charts-react/CHANGELOG.md
packages/synchro-charts-react/package.json
packages/synchro-charts/CHANGELOG.md
packages/synchro-charts/package.json
yarn.lock

release version 6.0.1

---

CHANGELOG.md
lerna.json
packages/doc-site/CHANGELOG.md
packages/doc-site/package.json
packages/synchro-charts-react/CHANGELOG.md
packages/synchro-charts-react/package.json
packages/synchro-charts/CHANGELOG.md
packages/synchro-charts/package.json

release version 6.0.2

---

CHANGELOG.md
lerna.json
packages/doc-site/CHANGELOG.md
packages/doc-site/package.json
packages/synchro-charts-react/CHANGELOG.md
packages/synchro-charts-react/package.json
packages/synchro-charts/CHANGELOG.md
packages/synchro-charts/package.json

release version 6.0.4

---

packages/doc-site/src/components/Dial.js
packages/doc-site/src/components/Dial.md
packages/synchro-charts-react/src/components.ts

Add dial doc.
Expose `Dial` react component

Add dial doc and expose a dial react component

---

.github/workflows/npm-publish.yml

change node version to fix broken builds

fix: node version changed from lte to 16.17.1

---

CHANGELOG.md
lerna.json
packages/doc-site/CHANGELOG.md
packages/doc-site/package.json
packages/synchro-charts-react/CHANGELOG.md
packages/synchro-charts-react/package.json
packages/synchro-charts/CHANGELOG.md
packages/synchro-charts/package.json

Release version 6.1.0

---

packages/doc-site/src/components/Gauge.js
packages/doc-site/src/components/Gauge.md
packages/synchro-charts-react/src/components.ts
packages/synchro-charts/src/components/sc-gauge/sc-gauge-base/sc-gauge-svg.tsx

feat(gauge-doc): Add gauge doc and gauge reaction component.
fix(gauge): The ring animation effect specifies a unique value(Fixed issue where when multiple gauge components are rendered together, only the last one will show animation).

feat(gauge-doc): Add gauge doc and gauge react component.

---

packages/synchro-charts/src/components/charts/sc-webgl-base-chart/sc-webgl-base-chart.tsx

prevent chart update if unsupported data is present, otherwise `onDataStreamsChange` the widget will try to find some containers which aren't present

fix: prevent update if unsupported data is present

---

CHANGELOG.md
lerna.json
packages/doc-site/CHANGELOG.md
packages/doc-site/package.json
packages/synchro-charts-react/CHANGELOG.md
packages/synchro-charts-react/package.json
packages/synchro-charts/CHANGELOG.md
packages/synchro-charts/package.json

release 7.1.0

---

.github/workflows/release-please.yml
.release-please-manifest.json
release-please-config.json

chore: setup release-please

---

.github/workflows/release-please.yml

Update release-please.yml - remove lock file update

Update release-please.yml - remove lock file update

---

.release-please-manifest.json
CHANGELOG.md
lerna.json
package.json
packages/doc-site/CHANGELOG.md
packages/doc-site/package.json
packages/synchro-charts-react/CHANGELOG.md
packages/synchro-charts-react/package.json
packages/synchro-charts/CHANGELOG.md
packages/synchro-charts/package.json

release version 7.1.2

---

packages/synchro-charts/src/components/sc-gauge/sc-gauge-base/sc-gauge-svg.tsx

[Provide an explanation of what the change is](fix: add space between value and unit) #206 

fix: add space between value and unit

---

packages/synchro-charts/cypress/integration/gauge/gauge.spec.ts
packages/synchro-charts/src/components/sc-dial/sc-dial-base/sc-dial-svg.tsx
packages/synchro-charts/src/components/sc-dial/sc-dial-base/svg-dial-svg.spec.tsx
packages/synchro-charts/src/components/sc-gauge/sc-gauge-base/sc-gauge-svg.tsx
packages/synchro-charts/src/components/sc-gauge/sc-gauge-base/svg-gauge-svg.spec.tsx

Provide an explanation of what the change is
fix: arc color should reflect the data stream color passed in #205 

fix: arc color should reflect the data stream color passed in

---

packages/synchro-charts/src/globals/awsui.css

Fixes a style bug where table rows are erroneously large.

fix(styles): fix table row height

---

packages/synchro-charts/src/components/charts/sc-webgl-base-chart/sc-webgl-base-chart.tsx

This will fix the missing scene issue by safeguard against race condition where the scene gets constructed and immediately removed.
first race condition:
- If componentDidUnload is called before componentDidLoad this.el.isConnected will be false
- This can happen when scrolling page very quickly
- If the component is unmounted before this.setupChartScene is complete we run into a race condition
where the scene gets created and assigned to this.scene but we override it with null before it
this.setupChartScene calls onUpdate
- Without the component mounted there is no point in calling onUpdate since we have nowhere to render this.scene
second race condition:
- if one of the watched props e.g. dataStreams changes this will call onUpdate
- if the component unmounts before this this.scene is …

fix: missing scene issue #255

---

.github/workflows/deploy-doc-site.yml
.github/workflows/github-actions.yml

update docsite yaml to use specific node version and bump `JamesIves/github-pages-deploy-action` to latest version

 chore(workflows): update workflow yaml node

---

CONTRIBUTING.md
design/base-chart.md
design/overview.md
packages/doc-site/docs/browserSupport.md
packages/doc-site/docs/developmentQuickStart.md
packages/doc-site/docs/introduction.md
packages/doc-site/docs/performance.md
packages/doc-site/docs/setup.md
packages/doc-site/docs/webglContext.md
packages/doc-site/package.json
packages/doc-site/styleguide.config.js
packages/iot-app-kit-visualizations-react/README.md
packages/iot-app-kit-visualizations-react/package.json
packages/iot-app-kit-visualizations/README.md
packages/iot-app-kit-visualizations/package.json
packages/iot-app-kit-visualizations/src/components/sc-webgl-context/webglContext.ts

remove mentions of synchro-charts in docs and ReadMes

chore: remove any mentions of synchro-charts

---

packages/iot-app-kit-visualizations/cypress/integration/charts/alarms.spec.ts
packages/iot-app-kit-visualizations/cypress/integration/charts/annotation-rescaling.spec.ts
packages/iot-app-kit-visualizations/cypress/integration/charts/bar-chart/draggable-annotations.spec.ts
packages/iot-app-kit-visualizations/cypress/integration/charts/line-chart/draggable-annotations.spec.ts
packages/iot-app-kit-visualizations/cypress/integration/charts/rendering-meshes.spec.ts
packages/iot-app-kit-visualizations/cypress/integration/charts/scatter-chart/draggable-annotations.spec.ts
packages/iot-app-kit-visualizations/cypress/integration/charts/status-timeline/threshold-legend.spec.ts
packages/iot-app-kit-visualizations/src/components/charts/sc-bar-chart/sc-bar-chart.tsx
packages/iot-app-kit-visualizations/src/components/charts/sc-legend/sc-legend.spec.tsx
packages/iot-app-kit-visualizations/src/components/charts/sc-line-chart/sc-line-chart.tsx
packages/iot-app-kit-visualizations/src/components/charts/sc-scatter-chart/sc-scatter-chart.tsx
packages/iot-app-kit-visualizations/src/components/charts/sc-status-timeline/sc-status-timeline.tsx
packages/iot-app-kit-visualizations/src/constants.ts

chore: remove exports

---

.release-please-manifest.json
packages/iot-app-kit-visualizations-react/CHANGELOG.md
packages/iot-app-kit-visualizations-react/package.json
packages/iot-app-kit-visualizations/package.json

only publish react components to NPM under name `@iot-app-kit/charts`

major: publish iot-app-kit/charts

---

.release-please-manifest.json
package.json
packages/iot-app-kit-visualizations-react/package.json
packages/iot-app-kit-visualizations/package.json
yarn.lock

Rename core package to `@iot-app-kit/charts-core` and make it public so we can import it in `@iot-app-kit/charts`

feat: rename core pckg to iot-app-kit/charts-core

---

README.md
packages/doc-site/docs/setup.md
packages/iot-app-kit-visualizations-react/package.json
packages/iot-app-kit-visualizations-react/src/components.ts
yarn.lock

replace synchro-charts `defineCustomElements, applyPolyfills, and JSX` with `@iot-app-kit/charts-core`

feat: replace synchro-charts in react package with charts-core

---

packages/iot-app-kit-visualizations/cypress/integration/charts/cross-resolution.spec.ts
packages/iot-app-kit-visualizations/cypress/integration/charts/scatter-chart/sc-webgl-scatter-chart.spec.ts
packages/iot-app-kit-visualizations/src/components.d.ts
packages/iot-app-kit-visualizations/src/components/charts/common/types.ts
packages/iot-app-kit-visualizations/src/components/charts/sc-tooltip/sc-tooltip-rows.spec.tsx
packages/iot-app-kit-visualizations/src/components/charts/sc-tooltip/sc-tooltip-rows.tsx
packages/iot-app-kit-visualizations/src/components/charts/sc-tooltip/sc-tooltip.css
packages/iot-app-kit-visualizations/src/components/charts/sc-tooltip/sc-tooltip.tsx
packages/iot-app-kit-visualizations/src/components/charts/sc-tooltip/types.ts
packages/iot-app-kit-visualizations/src/components/charts/sc-webgl-base-chart/sc-webgl-base-chart.tsx

portaling out tooltips so they dont mess with iot-app-kit/dashboard z-index

feat: portal tooltips

---

packages/iot-app-kit-visualizations/src/components/charts/sc-tooltip/sc-tooltip-rows.tsx
packages/iot-app-kit-visualizations/src/components/charts/sc-tooltip/sc-tooltip.tsx

no visual change but will ensure that tooltip will be positioned properly when chart isnt against left of viewport

fix: add left position to tooltip

---

packages/iot-app-kit-visualizations/src/components.d.ts
packages/iot-app-kit-visualizations/src/components/charts/sc-tooltip/sc-tooltip.tsx

Bug fix for tooltip where listeners are not attached if the dataContainer element is not available at render time.

fix(core): refactor listener registration for tooltip

---

packages/iot-app-kit-visualizations/src/components.d.ts
packages/iot-app-kit-visualizations/src/components/common/webGLPositioning.spec.ts
packages/iot-app-kit-visualizations/src/components/common/webGLPositioning.ts
packages/iot-app-kit-visualizations/src/components/sc-size-provider/sc-size-provider.tsx
packages/iot-app-kit-visualizations/src/components/sc-webgl-context/sc-webgl-context.tsx
packages/iot-app-kit-visualizations/src/components/sc-webgl-context/viewFrame.ts
packages/iot-app-kit-visualizations/src/components/sc-webgl-context/webglContext.spec.ts
packages/iot-app-kit-visualizations/src/components/sc-webgl-context/webglContext.ts

Update webgl positioning functions to make use of the viewframe passed to the webglcontext. 

fix(core): refactor webgl positioning to account for webglcontext viewframe

---

packages/iot-app-kit-visualizations/src/components/charts/sc-webgl-base-chart/UnsupportedDataTypeStatus.tsx
packages/iot-app-kit-visualizations/src/components/charts/sc-webgl-base-chart/sc-webgl-base-chart.tsx

Move check for is loading into UnsupportedData component

fix: unsupported data check if loading

---

packages/iot-app-kit-visualizations/src/components.d.ts
packages/iot-app-kit-visualizations/src/components/charts/common/types.ts
packages/iot-app-kit-visualizations/src/components/charts/sc-bar-chart/sc-bar-chart.tsx
packages/iot-app-kit-visualizations/src/components/charts/sc-line-chart/sc-line-chart.tsx
packages/iot-app-kit-visualizations/src/components/charts/sc-scatter-chart/sc-scatter-chart.tsx
packages/iot-app-kit-visualizations/src/components/charts/sc-status-timeline/sc-status-timeline.tsx
packages/iot-app-kit-visualizations/src/components/charts/sc-tooltip/sc-tooltip-rows.tsx
packages/iot-app-kit-visualizations/src/components/charts/sc-tooltip/sc-tooltip.tsx
packages/iot-app-kit-visualizations/src/components/charts/sc-webgl-base-chart/sc-webgl-base-chart.tsx

charts have an optional aggregationType prop

feat: charts accept aggregationType prop

---

packages/doc-site/docs/properties.md

fix(docs): update dataStream docs

---

packages/iot-app-kit-visualizations/src/components.d.ts
packages/iot-app-kit-visualizations/src/components/charts/common/types.ts
packages/iot-app-kit-visualizations/src/components/charts/sc-bar-chart/sc-bar-chart.tsx
packages/iot-app-kit-visualizations/src/components/charts/sc-line-chart/sc-line-chart.tsx
packages/iot-app-kit-visualizations/src/components/charts/sc-scatter-chart/sc-scatter-chart.tsx
packages/iot-app-kit-visualizations/src/components/charts/sc-status-timeline/sc-status-timeline-overlay/sc-status-timeline-overlay-row.tsx
packages/iot-app-kit-visualizations/src/components/charts/sc-status-timeline/sc-status-timeline-overlay/sc-status-timeline-overlay.tsx
packages/iot-app-kit-visualizations/src/components/charts/sc-status-timeline/sc-status-timeline.tsx
packages/iot-app-kit-visualizations/src/components/charts/sc-tooltip/sc-tooltip-row.tsx
packages/iot-app-kit-visualizations/src/components/charts/sc-tooltip/sc-tooltip-rows.tsx
packages/iot-app-kit-visualizations/src/components/charts/sc-tooltip/sc-tooltip.tsx
packages/iot-app-kit-visualizations/src/components/charts/sc-webgl-base-chart/sc-webgl-base-chart.tsx
packages/iot-app-kit-visualizations/src/components/value/Value.tsx
packages/iot-app-kit-visualizations/src/utils/number.ts

Add significant digits configuration for line / scatter / bar / status-timeline.

feat(visualizations): add significant digit configuration

---

.release-please-manifest.json
CHANGELOG.md
package.json
packages/iot-app-kit-visualizations-react/CHANGELOG.md
packages/iot-app-kit-visualizations-react/package.json
packages/iot-app-kit-visualizations/CHANGELOG.md
packages/iot-app-kit-visualizations/package.json

chore: release 2.1.2

---

.release-please-manifest.json
CHANGELOG.md
package.json
packages/iot-app-kit-visualizations-react/CHANGELOG.md
packages/iot-app-kit-visualizations-react/package.json
packages/iot-app-kit-visualizations/CHANGELOG.md
packages/iot-app-kit-visualizations/package.json

chore: release 2.1.3

---

.release-please-manifest.json
CHANGELOG.md
package.json
packages/synchro-charts-react/CHANGELOG.md
packages/synchro-charts-react/package.json
packages/synchro-charts/CHANGELOG.md
packages/synchro-charts/package.json

chore: release 7.1.7
