packages/doc-site/docs/webglContext.md, packages/synchro-charts/src/components.d.ts, packages/synchro-charts/src/components/sc-webgl-context/sc-webgl-context.tsx, packages/synchro-charts/src/components/sc-webgl-context/webglContext.spec.ts, packages/synchro-charts/src/components/sc-webgl-context/webglContext.ts
Currently, synchro-charts library users don't have access to the underlying WebGLRenderingContext. Being able to configure this context object is important for debugging - see utilities such as [WebGL Lint](https://greggman.github.io/webgl-lint/) and [WebGLDeveloperTools](https://github.com/KhronosGroup/WebGLDeveloperTools).
This proposed change adds an `onContextInitialization` hook that allows users to pass in their own callbacks that is able to access context post-initialization.
https://github.com/boweihan/synchro-charts/actions/runs/1400137561
=> [Draft] onContextInitialization

.github/workflows/deploy-doc-site.yml, packages/doc-site/README.md, packages/doc-site/assets/CNAME, packages/doc-site/styleguide.config.js
The documentation site for synchro-charts is currently being manually deployed. This change adds a GitHub action that does the following:
On push:
- Checks out the repo
- Installs and builds the doc site with yarn
- Deploys the `docs` folder to the `docs-cd` branch
In addition, the doc-site build has been configured to copy over a CNAME file which will help GitHub pages resolve DNS to a custom domain (in this case, `synchrocharts.com`).
Tests - https://github.com/boweihan/synchro-charts/actions/runs/1426511854
Deployment - https://github.com/boweihan/synchro-charts/runs/4119549911?check_suite_focus=true
=> [CI/CD] Continuously deploy documentation site on push

lerna.json, packages/doc-site/package.json, packages/synchro-charts-react/package.json, packages/synchro-charts/package.json, packages/synchro-charts/src/components.d.ts, packages/synchro-charts/src/components/sc-size-provider/sc-size-provider.tsx, packages/synchro-charts/src/interface.d.ts, packages/synchro-charts/src/utils/types.ts
- increasing minor versions and correcting version to be consistent across all packages
- Remove unused typescript types
- Fix size-provider such that it imports `Size`, which as an effect will fix the generation of the `components.d.ts` file which was previously generating a file with an unresolved type `Size`.
https://github.com/awslabs/synchro-charts/runs/4155627052?check_suite_focus=true
=> Fix exported component types; version bump

packages/synchro-charts/cypress/integration/charts/line-chart/sc-webgl-chart.spec.ts, packages/synchro-charts/src/components/charts/sc-webgl-base-chart/sc-webgl-base-chart.spec.tsx, packages/synchro-charts/src/components/charts/sc-webgl-base-chart/sc-webgl-base-chart.tsx, packages/synchro-charts/src/testing/test-routes/charts/line-chart-viewport-change.tsx
Currently, when the viewport duration of a "live" base chart is updated (i.e. `{ duration: '5m'} to {duration: '10m'}`, the chart remains updated for a single tick before the new configuration gets overwritten by the old configuration.
This is happening because we are calling `webGLRenderer.startTick` to start a new time loop without first calling `webGLRenderer.stopTick`.
```typescript
// sc-webgl-base-chart.tsx - line:301
if (this.scene != null && duration != null) {
webGLRenderer.stopTick({ manager: this.scene });  // <-- added in this PR
webGLRenderer.startTick({ manager: this.scene, duration, chartSize: this.chartSizeConfig() });
}
// viewportHandler.ts - line:45
if (liveIdKey in this.viewportLiveId) {
return; // duration update not registered to the ticker
}
```
This CR ensures we …
=> Support viewport duration updates on base charts

CHANGELOG.md, lerna.json, packages/doc-site/CHANGELOG.md, packages/doc-site/package.json, packages/synchro-charts-react/CHANGELOG.md, packages/synchro-charts-react/package.json, packages/synchro-charts/CHANGELOG.MD, packages/synchro-charts/package.json, packages/synchro-charts/src/components/charts/sc-status-timeline/sc-status-timeline.tsx
Address a bug which was the root cause of https://github.com/awslabs/synchro-charts/issues/111 - the status timeline would 'jitter', due to a new reference being generated on every render.
* prevent `status-timeline` from creating a new viewport reference on every render
* increase version to 1.0.8
=> fix: prevent status-timeline from regenerating new viewport on every render

lerna.json, packages/doc-site/docs/properties.md, packages/doc-site/package.json, packages/synchro-charts-react/package.json, packages/synchro-charts/package.json, packages/synchro-charts/src/components/charts/sc-webgl-base-chart/sc-webgl-base-chart.tsx
Minor documentation fix around datastreams, remove references to the removed `dataStreamInfo` concept.
=> fix: correct datastream documentation

.github/workflows/deploy-doc-site.yml
Deploy docs only on push to main
none
=> feat: Deploy docs only on push to main

CHANGELOG.md, lerna.json, packages/synchro-charts/CHANGELOG.MD, packages/synchro-charts/package.json, packages/synchro-charts/src/components/charts/sc-webgl-base-chart/sc-webgl-base-chart.tsx, packages/synchro-charts/src/components/viewportHandler/viewportHandler.spec.ts, packages/synchro-charts/src/components/viewportHandler/viewportHandler.ts
* Remove preventPropagation flag so events are always propagated to all members of a viewport group
* bump major version number due to breaking behavior change
[Unit Tests](https://github.com/awslabs/synchro-charts/runs/5346110552?check_suite_focus=true)
[Integ Tests](https://github.com/awslabs/synchro-charts/runs/5346110518?check_suite_focus=true)
=> Remove prevent propagation

CHANGELOG.md, lerna.json, packages/doc-site/CHANGELOG.md, packages/doc-site/package.json, packages/synchro-charts-react/CHANGELOG.md, packages/synchro-charts-react/package.json, packages/synchro-charts/CHANGELOG.MD, packages/synchro-charts/package.json, packages/synchro-charts/src/components/sc-widget-grid/sc-widget-grid.spec.ts, packages/synchro-charts/src/components/sc-widget-grid/sc-widget-grid.tsx
Support for displaying aggregated data in KPI and Status grid. Remove assumption that all alarm data must always be raw data.
=> feat: Add support for aggregated data in KPI and status grid

CHANGELOG.md, lerna.json, packages/doc-site/CHANGELOG.md, packages/doc-site/package.json, packages/synchro-charts-react/CHANGELOG.md, packages/synchro-charts-react/package.json, packages/synchro-charts/CHANGELOG.MD, packages/synchro-charts/package.json, packages/synchro-charts/src/components.d.ts, packages/synchro-charts/src/components/charts/sc-bar-chart/sc-bar-chart.tsx, packages/synchro-charts/src/components/charts/sc-line-chart/sc-line-chart.tsx, packages/synchro-charts/src/components/charts/sc-scatter-chart/sc-scatter-chart.tsx, packages/synchro-charts/src/components/charts/sc-status-timeline/sc-status-timeline.tsx, packages/synchro-charts/src/components/charts/sc-webgl-base-chart/sc-webgl-base-chart.tsx, packages/synchro-charts/src/components/common/constants.ts, packages/synchro-charts/src/components/sc-table/constructTableData.spec.ts, packages/synchro-charts/src/components/sc-table/constructTableData.ts, packages/synchro-charts/src/components/sc-table/sc-table-cell/sc-table-cell.spec.tsx, packages/synchro-charts/src/components/sc-table/sc-table-cell/sc-table-cell.tsx, packages/synchro-charts/src/components/sc-table/sc-table.tsx, packages/synchro-charts/src/components/sc-widget-grid/sc-widget-grid.tsx, packages/synchro-charts/src/testing/chartDescriptions/describePassedInProps.tsx, packages/synchro-charts/src/utils/dataTypes.ts
- support aggregations in table
- emit dateRangeChange event on synchronized viewport changes: On events like pan, every widget within the `viewport.group` will now emit a `dateRangeChange` event. This is a breaking change.
- Deprecate the undocumented method, `requestData`. SynchroCharts is no longer concerned about the data requesting layer. If users want to replicate this behavior, it can be done instead by listening to the `dateRangeChange` method.
- update to version 4.0.0, due to breaking changes.
=> v4.0.0: dateRangeChange, table aggregation, deprecate onRequestData

packages/doc-site/docs/properties.md
=> fix: typo in docs associatedStreams

packages/synchro-charts/src/components/charts/sc-webgl-base-chart/sc-webgl-base-chart.tsx
Provides a fix for https://github.com/awslabs/iot-app-kit/issues/107
When the amount of data surpasses the default buffer allocated for a chart, it must create a new chart scene with a larger amount of memory. This is the memory where vertex data is passed down into WebGL, and is used to render the WebGL portion of the chart visualization.
When the new chart scene is added in this scenario, it was incorrectly not supplying the chart size, which is required for live mode to work. This is because live mode uses the width of the chart, to determine the update frequency.
=> fix: live mode when buffer size increases on webgl based charts

packages/synchro-charts/src/components/charts/sc-webgl-base-chart/sc-webgl-base-chart.spec.tsx, packages/synchro-charts/src/components/charts/sc-webgl-base-chart/sc-webgl-base-chart.tsx, packages/synchro-charts/src/components/charts/sc-webgl-base-chart/utils.ts, packages/synchro-charts/src/components/viewportHandler/types.ts, packages/synchro-charts/src/components/viewportHandler/viewportHandler.spec.ts, packages/synchro-charts/src/components/viewportHandler/viewportHandler.ts
Fixes https://github.com/awslabs/synchro-charts/issues/150.
When in live mode, the viewportHandler tick cycle was passing the updated viewport back to the rendered chart. The logic was set to emit the `dateRangeChange` event any time the viewport changed. When in live mode this isn't the desired behavior so a flag was added to be able to check for that and block the event from being emitted.
=> Fix #150: dateRangeChange incorrectly called

packages/doc-site/docs/demo.md, packages/doc-site/docs/introduction.md, packages/doc-site/docs/liveMode.md, packages/doc-site/docs/properties.md, packages/doc-site/src/components/chart-demo/LiveDemo.jsx, packages/synchro-charts/src/utils/dataTypes.ts
- add optional field `meta` in `DataStream` type
- Add `meta` related documentation to doc-site
- Clean up doc-site to not have strange rendering
=> feat: Add new meta field on datastreams; clean doc-site

packages/synchro-charts/package.json, packages/synchro-charts/postinstall.js, yarn.lock
d3-color 1.x is affected by [a CVE](https://security.snyk.io/vuln/SNYK-JS-D3COLOR-1076592). It is patched [only in 3.1.0](https://github.com/d3/d3-brush/issues/90) and the maintainer [refuses to backport the fix](https://github.com/d3/d3-color/issues/108), so we need to upgrade.
d3-color is a dependency of several of our dependencies that specify 1.x, so we need to force resolution to 3.1.0 in package.json. This is fine because 2 and 3 merely [drop support for old environments](https://github.com/d3/d3-color/releases) that we [already disallow](https://github.com/awslabs/synchro-charts/blob/main/package.json#L10) and do not introduce any other relevant breaking changes.
The only caveat is that newer versions switch to using the ESM source code as the package default export and expose the …
=> chore: bump d3-color to 3.1.0, add postinstall hook to fix export path

packages/synchro-charts/package.json, yarn.lock
Implements a better version of the fix from #167. The maintainer of the package with the issue will not backport the fix to 1.x and [recommends](https://github.com/d3/d3-color/issues/108#issuecomment-1271705762) forking the package, and [other major projects](https://github.com/recharts/recharts/issues/3012#issuecomment-1284393411) are discussing forking the package as well.
Here I have forked the package, cherry-picked the fix onto 1.4.x, and published as a new package at 1.4.2. Then, we resolve `d3-color` to that package with [yarn's `resolutions` feature](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/#toc-why-would-you-want-to-do-this) (the second bullet point there describes our situation exactly).
This project is available under the [Apache 2.0 …
=> fix: switch to fork of d3-color 1.4.x with backtracking fix from 3.1.0 applied

packages/doc-site/package.json, packages/synchro-charts/package.json, yarn.lock
Resolves minimatch to 3.0.5 and addresses [resolutions field issue with Yarn 1.22](https://github.com/yarnpkg/yarn/issues/7680#issuecomment-967025399) for d3-color fork.
=> chore: bump and resolve minimatch to 3.0.5, resolve d3-color-1-fix to npm

CHANGELOG.md, lerna.json, packages/doc-site/CHANGELOG.md, packages/doc-site/package.json, packages/synchro-charts-react/CHANGELOG.md, packages/synchro-charts-react/package.json, packages/synchro-charts/CHANGELOG.md, packages/synchro-charts/package.json
=> Release version 6.0.5

packages/synchro-charts/src/components/charts/common/annotations/utils.ts, packages/synchro-charts/src/components/charts/common/types.ts, packages/synchro-charts/src/components/charts/sc-tooltip/sort.ts, packages/synchro-charts/src/components/sc-widget-grid/sc-grid-tooltip.tsx, packages/synchro-charts/src/components/value/Value.tsx, packages/synchro-charts/src/utils/dataTypes.ts
allows for booleans in data, alarms, and annotations
KPI
Grid
Timeline
Table
=> feat: add boolean primitive type

packages/synchro-charts/src/components.d.ts, packages/synchro-charts/src/components/sc-dial/sc-dial-base/sc-dial-base.tsx, packages/synchro-charts/src/components/sc-dial/utils/type.ts, packages/synchro-charts/src/components/sc-dial/utils/util.ts, packages/synchro-charts/src/components/sc-widget-grid/sc-grid-tooltip.tsx
Added input parameters at(sc-grid-tooltip): 
Two more inputs, `value`(optional) and `unit`(optional), are added.  
Changed the input parameter type of `messageOverrides` to solve the problem of hard coding.
=> feat(sc-grid-tooltip): Added input parameters

packages/doc-site/docs/threshold.md, packages/doc-site/src/components/StatusGrid.md, packages/doc-site/src/components/Table.md, packages/synchro-charts/src/components/charts/common/annotations/utils.spec.ts, packages/synchro-charts/src/components/charts/common/annotations/utils.ts, packages/synchro-charts/src/components/charts/common/constants.ts, packages/synchro-charts/src/utils/dataTypes.ts, packages/synchro-charts/src/utils/number.spec.ts, packages/synchro-charts/src/utils/number.ts
Adds a `contains` operator to thresholds and documentation for threshold strings and arrays of strings. Also noticed a typo of `temperature`, so updated that.
In order to extend the use case of matching strings, we're adding the ability for the user to match part of a threshold string. We've also extended the string matching to match at least one string in an array.
For example, if using the `contains` operator and the threshold value is `STOP` and the data value is `STOPPED`, the threshold will be breached.
If using the `contains` operator and the threshold value is an array of strings, like [`STOP`, `WARNING`], and the data value is `STOPPED`, the threshold will be breached.
This project is available under the …
=> feat: add 'contains' operator to thresholds.

packages/synchro-charts/src/components/charts/sc-webgl-base-chart/sc-webgl-base-chart.tsx
moving the check for `hasSupportedData` since some `onUpdate` calls were still causing errors in appkit
=> chore: move check for unsupported data

packages/synchro-charts/src/components/sc-table/sc-table.tsx, packages/synchro-charts/src/components/sc-widget-grid/sc-widget-grid.tsx, packages/synchro-charts/src/components/viewportHandler/viewportHandler.spec.ts, packages/synchro-charts/src/components/viewportHandler/viewportHandler.ts, packages/synchro-charts/src/utils/viewPort.spec.ts, packages/synchro-charts/src/utils/viewPort.ts
do not call dateRangeChange in live mode
=> fix: do not call dateRangeChange in live mode

packages/synchro-charts/src/components/sc-dial/sc-dial-base/sc-dial-svg.tsx, packages/synchro-charts/src/components/sc-gauge/sc-gauge-base/sc-gauge-svg.tsx
fix(dial/gauge): remove transitions entirely. https://github.com/awslabs/synchro-charts/issues/204 
=> fix(dial/gauge): remove transitions entirely

packages/synchro-charts/src/components/charts/sc-webgl-base-chart/sc-webgl-base-chart.tsx
stop onUpdate if scene does not exist instead of throwing an error
=> fix: stop onUpdate if scene does not exist

packages/synchro-charts/src/components/sc-gauge/sc-gauge.tsx
Provide an explanation of what the change is (gauge)
fix: threshold outside of y range rendering bug #199 
fix: negative yMin while threshold is present causes incorrect rendering of threshold arc #203
=> fix: threshold outside of y range include negative yMin rendering bug

.github/workflows/deploy-doc-site.yml
bump down github-pages-deploy-action to 4.1.5
=> chore{workflow): bump down github-pages-deploy-action

packages/iot-app-kit-visualizations/src/components/charts/common/types.ts
`colorDataAcrossThresholds` is no longer used. Should use `thresholdOptions` instead.
=> chore: remove deprecated `colorDataAcrossThresholds` flag

packages/iot-app-kit-visualizations-react/package.json
remove reference to `iot-app-kit-vis/core` in `iot-app-kit/charts` copy styles script
which broke the NPM publish step
=> feat(react): fix broken copy styles script

packages/iot-app-kit-visualizations/src/components/charts/sc-webgl-base-chart/sc-webgl-base-chart.tsx, packages/iot-app-kit-visualizations/src/components/common/constants.ts
- Throttle setViewport function call
- Fix bug where viewport would jump back to live mode if a gesture was made and new data was added
=> fix(base-chart): fix gesture+live mode bug and throttle

packages/iot-app-kit-visualizations/src/components/charts/sc-legend/sc-legend-row/sc-legend-row.tsx
=> fix(legend): fix name and unit gap in legend

packages/iot-app-kit-visualizations/src/components/charts/sc-webgl-base-chart/UnsupportedDataTypeStatus.tsx, packages/iot-app-kit-visualizations/src/components/charts/sc-webgl-base-chart/sc-webgl-base-chart.spec.tsx, packages/iot-app-kit-visualizations/src/components/charts/sc-webgl-base-chart/sc-webgl-base-chart.tsx, packages/iot-app-kit-visualizations/src/testing/chartDescriptions/describeLegend.tsx
fix legend spacing
fix flash of error state when widg
et is first added
=> fix: hide legend and error state on loading or empty state

packages/iot-app-kit-visualizations/src/components/charts/sc-webgl-base-chart/sc-webgl-base-chart.tsx
check if data is loading before checking if dataStream type is unsupported
=> fix: check if data is loading for unsupported types

.github/dependabot.yml, .github/workflows/dependabot-hook.yml
This change enables a turbo-charged Dependabot with the following changes:
- Enable up to 25 dependency version bumps a day.
- Enable GitHub Actions version bumps.
- Auto-approve version bump PRs.
- Enable auto-merge with rebase on version bump PRs.
The work automates dependency updates. Dependency updates will only need to be manually touched if a required check fails. If required checks fail, it's often easiest to just close the PR, unless we really want the update.
=> ci: enable turbo-charged dependabot

packages/iot-app-kit-visualizations/src/components/charts/sc-status-timeline/sc-threshold-legend/sc-threshold-legend.spec.ts, packages/iot-app-kit-visualizations/src/components/charts/sc-status-timeline/sc-threshold-legend/sc-threshold-legend.tsx
bugfix for status-timeline threshold label. Use the passed in label instead of the comparator and value if present and show is true.
=> fix(visualizations): use passed in label in status-timeline component

packages/iot-app-kit-visualizations/src/components/charts/sc-webgl-base-chart/sc-webgl-base-chart.tsx
unsupported data streams check was running against datastreams which do not yet have the dataType property. this caused the check to return that it does have unsupported datastreams since undefined was not in the list.
=> fix(base-chart): only check datastreams with data types in unsupported check
